# Generated by Django 5.1.2 on 2025-03-13 01:15

import django.core.validators
import mpesa_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID number', max_length=8, null=True, unique=True, validators=[mpesa_application.models.validate_kenyan_id]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+254XXXXXXXXX'", regex='^\\+?254\\d{9}$')]),
        ),
    ]
