# Generated by Django 5.1.2 on 2025-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_application', '0006_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
