# Generated by Django 5.1.2 on 2025-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_application', '0008_loan_status_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='limit',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('AIRTIME', 'Airtime Purchase'), ('BILLPAY', 'Bill Payment'), ('LOAN', 'loan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('AIRTIME', 'Airtime Purchase'), ('BILLPAY', 'Bill Payment'), ('LOAN', 'loan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('AIRTIME', 'Airtime Purchase'), ('BILLPAY', 'Bill Payment'), ('LOAN', 'loan')], max_length=10),
        ),
    ]
